### ISSUE TITLE
No fingerprint enrolled crash

### ISSUE THREAD

**Issue by cloudshooterhuman** [googlesamples/android-AsymmetricFingerprintDialog#5]
Got this crash after restarting the emulator :

```
ComponentInfo{com.example.android.asymmetricfingerprintdialog/com.example.android.asymmetricfingerprintdialog.MainActivity}: java.lang.RuntimeException: 
java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
                                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                                  Caused by: java.lang.RuntimeException: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
                                                                                                     at com.example.android.asymmetricfingerprintdialog.MainActivity.createKeyPair(MainActivity.java:194)
                                                                                                     at com.example.android.asymmetricfingerprintdialog.MainActivity.onCreate(MainActivity.java:93)
                                                                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                                  Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
                                                                                                     at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.initialize(AndroidKeyStoreKeyPairGeneratorSpi.java:339)
                                                                                                     at java.security.KeyPairGenerator$KeyPairGeneratorImpl.initialize(KeyPairGenerator.java:284)
                                                                                                     at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:192)
                                                                                                     at com.example.android.asymmetricfingerprintdialog.MainActivity.createKeyPair(MainActivity.java:183)
                                                                                                     at com.example.android.asymmetricfingerprintdialog.MainActivity.onCreate(MainActivity.java:93) 
                                                                                                     at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                                  Caused by: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
                                                                                                     at android.security.keystore.KeymasterUtils.addUserAuthArgs(KeymasterUtils.java:115)
                                                                                                     at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.initialize(AndroidKeyStoreKeyPairGeneratorSpi.java:335)
                                                                                                     at java.security.KeyPairGenerator$KeyPairGeneratorImpl.initialize(KeyPairGenerator.java:284) 
                                                                                                     at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:192) 
                                                                                                     at com.example.android.asymmetricfingerprintdialog.MainActivity.createKeyPair(MainActivity.java:183) 
                                                                                                     at com.example.android.asymmetricfingerprintdialog.MainActivity.onCreate(MainActivity.java:93) 
                                                                                                     at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Comment by codingjeremy** [comment]
This sample has been updated to Kotlin and migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
