### ISSUE TITLE
android.permission.INTERACT_ACROSS_USERS Permission Denial crash for non-fingerprint device

### ISSUE THREAD

**Issue by ildar2** [googlesamples/android-AsymmetricFingerprintDialog#9]
Started fresh app and it cannot even launch on a device without fingerprint scanner
```
com.example.android.asymmetricfingerprintdialog E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.asymmetricfingerprintdialog, PID: 20003
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.asymmetricfingerprintdialog/com.example.android.asymmetricfingerprintdialog.MainActivity}: java.lang.SecurityException: Permission Denial: getCurrentUser() from pid=20003, uid=10183 requires android.permission.INTERACT_ACROSS_USERS
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
        at android.app.ActivityThread.access$1100(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7329)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.SecurityException: Permission Denial: getCurrentUser() from pid=20003, uid=10183 requires android.permission.INTERACT_ACROSS_USERS
        at android.os.Parcel.readException(Parcel.java:1621)
        at android.os.Parcel.readException(Parcel.java:1574)
        at android.hardware.fingerprint.IFingerprintService$Stub$Proxy.hasEnrolledFingerprints(IFingerprintService.java:503)
        at android.hardware.fingerprint.FingerprintManager.hasEnrolledFingerprints(FingerprintManager.java:768)
        at com.example.android.asymmetricfingerprintdialog.MainActivity.onCreate(MainActivity.java:85)
        at android.app.Activity.performCreate(Activity.java:6904)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7329) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

**Comment by esunilkumare** [comment]
I am also facing a similar issue

**Comment by guness** [comment]
looks like this one:
https://stackoverflow.com/a/38179997

**Comment by codingjeremy** [comment]
This sample has been updated to Kotlin and migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
